### ISSUE TITLE
Document source of samples to protect against copyright infringement 

### ISSUE THREAD

**Issue by matthewarmand** [TheSmallTeaBoi/the-libre-sample-pack#1]
This is a cool idea for a project, and good on you for taking the initiative. However, this piece of the `README` is a huge red flag:

> Due to the nature of the project, I have little to no way of checking if all samples/presets are free to use, so all of it is based on the trust.

If you're claiming this sample pack is "libre" and all the open source buzzword goodness, you need to be sure that they actually are "free to use". Anything less  could potentially open users up to copyright infringement without knowing it. I'll refer you also to a [comment posted to your r/linuxaudio post](https://www.reddit.com/r/linuxaudio/comments/iew9c3/i_present_to_you_the_libre_sample_pack/g2ki3aj).

**Comment by TheSmallTeaBoi** [comment]
I will quote my reddit reply here:
> I guess that I should have worded that differently, all the samples/presets uploaded by me are free and made by me, but I don't have that many ways of checking if other people's contributions are made by them or not. ¯\\\_(ツ)_/¯

I will also tag all samples/presets uploaded by me so you can work safe :D

**Comment by TheSmallTeaBoi** [comment]
I have added a `trusted contributors` list, anything uploaded from them, is checked to be free to use. I consider this to be enough, so I am closing this issue.
