### ISSUE TITLE
Redundant with other projects ?

### ISSUE THREAD

**Issue by BrunoVernay** [TheSmallTeaBoi/the-libre-sample-pack#4]
- Tons of resources free: [https://Musical-Artifacts.com/](https://musical-artifacts.com/)
- From [[Polyphone]] 
    - "and repository https://www.polyphone-soundfonts.com/download-soundfonts"
- Free SoundBanks http://freepats.zenvoid.org/
- https://samplefocus.com/
    - Very nice navigation, just hovering a sample plays it!
- https://FreeWaveSamples.com/
- https://sites.google.com/site/soundfonts4u/
    - A bit old looking, but still updated as of November 2020.
- https://FreeSound.org/
- "Conserve the sound" http://www.conservethesound.de/
    - Online museum for vanishing and endangered sounds. The sound of a dial telephone, a walkman, a analog typewriter, a pay phone, a 56k modem, a nuclear power plant or even a cell phone keypad are partially already gone or are about to disappear from our daily life.
- [https://CitiesAndMemory.com/sound-map/](https://citiesandmemory.com/sound-map/)

**Comment by TheSmallTeaBoi** [comment]
While yes, there are already a lot of free samples sources, I don't think there is any linux-oriented plugin preset collection. You could also argue these pages are redundant between each other as well.

**Comment by BrunoVernay** [comment]
Indeed, the preset collection is more unique.  (I am not trying to fight duplication, but I was only 90% sure you knew about these sites.)
